spring.application.name=findashboard

# Database Connection
# We use the placeholders so Render can inject the values
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# Hibernate / JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-className=com.mysql.cj.jdbc.Driver

# Required for Render to bind to the correct port
server.port=${PORT:8080}